// Note: Generated by AI, needs verification
import { App, h, createApp, defineComponent, nextTick } from 'vue';

// 判断对象是否为Object类型
// Determine if the object is of Object type
function isObject(obj: unknown): obj is Record<string, unknown> {
    return Object.prototype.toString.call(obj) === '[object Object]';
}

export interface RootType {
    render: (container: HTMLElement) => void;
    unmount: () => void;
}

// Vue 3 提供的创建应用实例方法
// The method provided by Vue 3 to create an app instance
const createVueApp = (
    component: ReturnType<typeof defineComponent>,
    props?: Record<string, unknown>,
) => {
    const container = document.createElement('div');
    const app = createApp(component, props);

    return {
        render: (mountContainer: HTMLElement) => {
            app.mount(mountContainer);
        },
        unmount: () => {
            app.unmount();
            if (container.parentNode) {
                container.parentNode.removeChild(container);
            }
        },
    };
};

export const render = createVueApp;
