// Note: Generated by AI, needs verification
// packages/arcodesign-vue/components/_helpers/hooks.ts

import { Ref, onMounted, onUnmounted, onBeforeUnmount, watch } from 'vue';

// 类似于React的useEffect钩子，在组件mounted和unmounted时运行副作用
export function useEffect(effect: () => (() => void) | void, dependencies?: Ref<any>[]) {
    onMounted(() => {
        const cleanup = effect();

        if (cleanup) {
            onBeforeUnmount(cleanup);
        }
    });

    // 如果提供依赖项数组参数，则为每个依赖项设置一个watcher观察者
    if (dependencies) {
        watch(dependencies, () => {
            const cleanup = effect();

            return () => {
                if (cleanup) cleanup();
            };
        });
    }
}

// 在Vue生命周期钩子used的钩子中使用
export function useLifecycle(lifecycle: 'mounted' | 'unmounted', callback: () => void) {
    if (lifecycle === 'mounted') {
        onMounted(callback);
    } else if (lifecycle === 'unmounted') {
        onUnmounted(callback);
    }
}
