// import { SourceCode } from './code.mjs';
import { AiBot } from './coze.mjs';

const BOT_ID = '7369473402367361041'; // GPT-4 模型
const TOKEN = process.env.COZE_TOKEN_ADM;

// const prompt1 = `

// 你是一个优秀的前端工程师，致力于为 Arco Design Mobile 做贡献，熟悉 React 和 Vue 框架，擅长将 React 代码改写为 Vue 代码

// 改写的要求有：
// - 组件的功能和表现应与 React 代码完全一致
// - 需要将 React 的 JSX/TSX 转换为 Vue 文件要使用模版语法
// - 生成的代码代码的首行需要添加注释 "Note: Generated by AI, needs verification"
// - 生成的代码需要添加中英文双语注释
// - 代码风格和命名习惯需要参考 Cell 组件和 Notify 组件的源代码

// 我会为你提供提供一些 2 个示例，你可以参考这两个示例的目录结构、代码风格和命名习惯

// 第一个是 Notify 组件示例，下面是 React 版本的源代码：
// ${getCode('packages/arcodesign/components/notify/', /.(ts|tsx|js|jsx|less)$/)}
// 将其转换为 Vue 版本后的代码
// ${getCode('packages/arcodesign-vue/components/notify/', /.(vue|ts|js|less)$/)}

// 第二个是 Cell 组件的示例，这是 React 版本的源代码：
// ${getCode('packages/arcodesign/components/cell/', /.(ts|tsx|js|jsx|less)$/)}
// 将其转换为 Vue 版本后的代码
// ${getCode('packages/arcodesign-vue/components/cell/', /.(vue|ts|js|less)$/)}

// 下面我给你提供一个全新的组件，这个组件名为 Loading ，React 版本源代码为
// ${getCode('packages/arcodesign/components/cell/', /.(ts|tsx|js|jsx|less)$/)}

// 现在需要将其转换为 Vue 版本，请你指导我完成这份工作，这个工作需要完成多个文件的源代码编写。

// 你需要一步一步教我完成全部的工作，每一步只需要完成一个文件的代码编写，你应该直接回复文件路径和文件内容。
// 每完成一个文件文件编写，我会发送"Next"，你应该继续回复下一个文件的路径和文件内容，以此类推，直到全部文件编写完成。
// 当全部工作完成之后，如果我继续发送 "Next"，你应该只回复 "DONE"

// `;

const prompt_game = `
现在我们玩一个游戏：

当我发送一个数字，你应该将这个数字+1，并将结果发给我。
当我发送 "Next"，你应该继续+1，并将结果发给我。
当再次接收到数字后，游戏重新开始。

严格按照游戏规则回复，不要回复其他内容。

首先我给你一个数字是 1

`;

const prompt_article = `
帮我随机写一篇文言文，大概200字左右

当我发送 "Next"，你需要继续扩写文章，增加 50 字左右
`;

///// 主流程开始 /////

const bot = new AiBot(BOT_ID, TOKEN);

await bot.chat('对对联，上联：回是口中口');
