// Note: Generated by AI, needs verification
import Loading from './Loading.vue';
import { installFactory } from '../_helpers/install';

const install = installFactory(Loading);

export { Loading };

export default {
    install,
};
