<!-- Note: Generated by AI, needs verification -->
<script lang="ts" setup>
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import { isOneOf } from '@arco-design/mobile-utils';
import { getPrefixCls } from '../context-provider';
import { LoadingProps } from './type';

defineOptions({
    name: 'Loading',
});

const props = withDefaults(defineProps<LoadingProps>(), {
    type: 'dot',
    duration: 1000,
    radius: 9,
    stroke: 2,
    filleted: true,
    svgKey: '',
});

const prefix = getPrefixCls('loading');
const statusList = ref<number[]>([]);
const timerId = ref<number>(-1);

// 计算属性
const halfCircle = computed(() => Math.PI * props.radius);
const circlePos = computed(() => 0.5 * props.stroke + props.radius);
const circleSize = computed(() => props.radius * 2 + props.stroke);
const actualSvgKey = computed(() => props.svgKey || `${Date.now()}-${Math.random()}`);

// 获取样式与浏览器前缀
function getStyleWithVendor(style: Record<string, any>) {
    return style;
}

// 动画逻辑
function startAnimation() {
    if (props.type === 'dot' && statusList.value.length) {
        const interval = props.duration / statusList.value.length;
        timerId.value = window.setInterval(() => {
            const newList = [...statusList.value];
            const item = newList.pop();
            if (item !== undefined) {
                newList.unshift(item);
            }
            statusList.value = newList;
        }, interval);
    }
}

function stopAnimation() {
    if (timerId.value >= 0) {
        clearInterval(timerId.value);
        timerId.value = -1;
    }
}

// 初始化状态列表
function initStatusList() {
    let newList: number[];
    if (props.list && props.list.length) {
        newList = props.list;
    } else {
        switch (props.type) {
            case 'spin':
                newList = [1, 0.1, 0.2286, 0.3572, 0.4858, 0.6144, 0.743, 0.8716];
                break;
            case 'dot':
                newList = [0.2, 0.6, 1];
                break;
            default:
                newList = [];
                break;
        }
    }
    statusList.value = newList;
}

// 渲染函数
const renderSpin = () => {
    const len = statusList.value.length;
    return statusList.value.map((opacity, index) => ({
        opacity,
        transform: `rotate(${index / len}turn)`,
        width: `${props.stroke}px`,
        backgroundColor: props.color,
        borderRadius: props.filleted ? `${props.stroke}px` : undefined,
    }));
};

const renderDot = () => {
    return statusList.value.map(opacity => ({
        opacity,
        backgroundColor: props.color,
    }));
};

// 计算样式
const loadingStyle = computed(() => {
    const circleStyle = isOneOf(props.type, ['circle', 'arc'])
        ? {
              width: `${circleSize.value}px`,
              height: `${circleSize.value}px`,
          }
        : {};
    return getStyleWithVendor({
        animationDuration: `${props.duration}ms`,
        ...circleStyle,
        ...(props.style || {}),
    });
});

// 生命周期
onMounted(() => {
    initStatusList();
    startAnimation();
});

onUnmounted(() => {
    stopAnimation();
});

// 监听器
watch([() => props.list, () => props.type], () => {
    stopAnimation();
    initStatusList();
    startAnimation();
});

watch([() => props.type, () => statusList.value, () => props.duration], () => {
    stopAnimation();
    startAnimation();
});
</script>

<template>
    <div :class="[`${prefix}`, 'all-border-box', props.type, props.class]" :style="loadingStyle">
        <!-- Spin 类型 -->
        <template v-if="props.type === 'spin'">
            <span
                v-for="(item, index) in renderSpin()"
                :key="index"
                class="spin-cell"
                :style="{
                    opacity: item.opacity,
                    transform: item.transform,
                    width: item.width,
                }"
            >
                <span
                    class="spin-cell-inner bg-color-with-config"
                    :style="{
                        backgroundColor: item.backgroundColor,
                        borderRadius: item.borderRadius,
                    }"
                />
            </span>
        </template>

        <!-- Dot 类型 -->
        <template v-if="props.type === 'dot'">
            <span
                v-for="(item, index) in renderDot()"
                :key="index"
                :class="['dot-cell', 'bg-color-with-config', { filleted: props.filleted }]"
                :style="{
                    opacity: item.opacity,
                    backgroundColor: item.backgroundColor,
                }"
            />
        </template>

        <!-- Circle 类型 -->
        <template v-if="props.type === 'circle'">
            <svg :viewBox="`0 0 ${circleSize} ${circleSize}`">
                <defs>
                    <linearGradient :id="`grad1-${actualSvgKey}`" x1="0%" y1="0%" x2="100%" y2="0%">
                        <stop
                            offset="0%"
                            class="loading-circle-middle stop-color-with-config"
                            :style="{ stopColor: props.color }"
                        />
                        <stop
                            offset="100%"
                            class="loading-circle-start stop-color-with-config"
                            :style="{ stopColor: props.color }"
                        />
                    </linearGradient>
                    <linearGradient :id="`grad2-${actualSvgKey}`" x1="0%" y1="0%" x2="100%" y2="0%">
                        <stop
                            offset="0%"
                            class="loading-circle-middle stop-color-with-config"
                            :style="{ stopColor: props.color }"
                        />
                        <stop
                            offset="100%"
                            class="loading-circle-end stop-color-with-config"
                            :style="{ stopColor: props.color }"
                        />
                    </linearGradient>
                </defs>
                <circle
                    :cx="circlePos"
                    :cy="circlePos"
                    :r="props.radius"
                    :stroke="`url(#grad1-${actualSvgKey})`"
                    :stroke-width="props.stroke"
                    :stroke-dasharray="halfCircle"
                    :stroke-dashoffset="halfCircle"
                    fill="none"
                />
                <circle
                    :cx="circlePos"
                    :cy="circlePos"
                    :r="props.radius"
                    :stroke="`url(#grad2-${actualSvgKey})`"
                    :stroke-width="props.stroke"
                    :stroke-dasharray="halfCircle"
                    fill="none"
                />
                <circle
                    v-if="props.filleted"
                    :cx="circlePos * 2 - props.stroke / 2"
                    :cy="circlePos"
                    :r="props.stroke / 2"
                    class="loading-circle-filleted fill-color-with-config"
                    :style="{ fill: props.color }"
                />
            </svg>
        </template>

        <!-- Arc 类型 -->
        <template v-if="props.type === 'arc'">
            <svg :viewBox="`0 0 ${circleSize} ${circleSize}`">
                <circle
                    class="arc-bg"
                    :cx="circlePos"
                    :cy="circlePos"
                    :r="props.radius"
                    :stroke-width="props.stroke"
                    fill="none"
                />
                <circle
                    class="arc-line stroke-color-with-config"
                    :cx="circlePos"
                    :cy="circlePos"
                    :r="props.radius"
                    :style="{ stroke: props.color }"
                    :stroke-width="props.stroke"
                    :stroke-dashoffset="halfCircle * 0.5"
                    :stroke-dasharray="`${halfCircle * 0.5} ${halfCircle * 1.5}`"
                    fill="none"
                    :stroke-linecap="props.filleted ? 'round' : undefined"
                />
            </svg>
        </template>
    </div>
</template>
