name: auto-release
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: npm install with cache
        uses: bahmutov/npm-install@v1

      - name: init lerna repo
        run: npm run init
      
      - name: lerna publish
        run: |
          git config user.name "{{ github.actor }}"
          git config user.email "{{ github.actor }}@users.noreply.github.com"
          npm run pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  